// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8A-zb5WBQhdCxK0csxTn3h5fTcOewd8',
    appId: '1:119904146680:web:b60e549ee6f769bfbb570d',
    messagingSenderId: '119904146680',
    projectId: 'homeservicesfypapp',
    authDomain: 'homeservicesfypapp.firebaseapp.com',
    storageBucket: 'homeservicesfypapp.appspot.com',
    measurementId: 'G-8P9HTXLGB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytN4JyCXVojQnfbJA0wCw6b-dl3Oxypk',
    appId: '1:119904146680:android:be5efcb3520898b7bb570d',
    messagingSenderId: '119904146680',
    projectId: 'homeservicesfypapp',
    storageBucket: 'homeservicesfypapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfg2Zn3ynoSh4hE3VstD-dQa4ExuJ0meI',
    appId: '1:119904146680:ios:d6bf936ee93058a0bb570d',
    messagingSenderId: '119904146680',
    projectId: 'homeservicesfypapp',
    storageBucket: 'homeservicesfypapp.appspot.com',
    iosClientId: '119904146680-v633hrd0dqjcgsnb2hhbut1s7cbqboop.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServicesFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfg2Zn3ynoSh4hE3VstD-dQa4ExuJ0meI',
    appId: '1:119904146680:ios:d6bf936ee93058a0bb570d',
    messagingSenderId: '119904146680',
    projectId: 'homeservicesfypapp',
    storageBucket: 'homeservicesfypapp.appspot.com',
    iosClientId: '119904146680-v633hrd0dqjcgsnb2hhbut1s7cbqboop.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServicesFyp',
  );
}
